/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f4',
        'surface-dim': '#e1d8d2',
        'surface-bright': '#fff8f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fcf2eb',
        'surface-container': '#f6ece5',
        'surface-container-high': '#f0e6e0',
        'surface-container-highest': '#eae1da',
        'on-surface': '#1f1b17',
        'on-surface-variant': '#4a4551',
        'inverse-surface': '#34302b',
        'inverse-on-surface': '#f9efe8',
        outline: '#7b7482',
        'outline-variant': '#ccc3d2',
        'surface-tint': '#6d4ca8',
        primary: '#1d0046',
        'on-primary': '#ffffff',
        'primary-container': '#350d6e',
        'on-primary-container': '#a07ede',
        'inverse-primary': '#d4bbff',
        secondary: '#6b38d4',
        'on-secondary': '#ffffff',
        'secondary-container': '#8455ee',
        'on-secondary-container': '#fffbff',
        tertiary: '#201100',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3b2400',
        'on-tertiary-container': '#c58200',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ebdcff',
        'primary-fixed-dim': '#d4bbff',
        'on-primary-fixed': '#260058',
        'on-primary-fixed-variant': '#54338e',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#5517be',
        'tertiary-fixed': '#ffddb4',
        'tertiary-fixed-dim': '#ffb955',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#633f00',
        background: '#fff8f4',
        'on-background': '#1f1b17',
        'surface-variant': '#eae1da',
        'ivory-bg': '#FAF7F2',
        'midnight-bg': '#0E0B14',
        'surface-warm': '#fff8f4',
        'status-healthy': '#10B981',
        'status-critical': '#EF4444',
        'warm-grey': '#E8E2D9',
        'accent-amber': '#F5A623',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'section-gap': '120px',
      },
      fontFamily: {
        fraunces: ['Fraunces', 'serif'],
        hanken: ['Hanken Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'display-lg': ['Fraunces', 'serif'],
        'display-lg-mobile': ['Fraunces', 'serif'],
        'headline-xl': ['Fraunces', 'serif'],
        'headline-lg': ['Fraunces', 'serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'code-sm': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
