/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Spec design tokens
        'violet-primary': '#4C2A85',
        'violet-accent': '#8B5CF6',
        cream: '#FAF7F2',
        'near-black': '#0E0B14',
        'warm-grey-100': '#E8E2D9',
        'warm-grey-600': '#6B6560',
        'warm-grey-700': '#5A5550',
        'amber-accent': '#F5A623',
        // Severities
        sev1: '#EF4444',
        sev2: '#F97316',
        sev3: '#F59E0B',
        sev4: '#64748B',
        // Outcomes
        'status-approved': '#22C55E',
        'status-pending': '#F59E0B',
        'status-rejected': '#EF4444',

        // Legacy / Fallback aliases
        surface: '#fff8f4',
        'surface-dim': '#e1d8d2',
        'surface-bright': '#fff8f4',
        'surface-container': '#f6ece5',
        'on-surface': '#1f1b17',
        'on-surface-variant': '#4a4551',
        outline: '#7b7482',
        'outline-variant': '#ccc3d2',
        primary: '#4C2A85',
        'primary-container': '#350d6e',
        secondary: '#8B5CF6',
        'secondary-fixed-dim': '#d0bcff',
        error: '#EF4444',
        background: '#fff8f4',
        'ivory-bg': '#FAF7F2',
        'midnight-bg': '#0E0B14',
        'status-healthy': '#22C55E',
        'status-critical': '#EF4444',
        'warm-grey': '#E8E2D9',
        'warm-grey-light': '#E8E2D9',
        'accent-amber': '#F5A623',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'section-gap': '120px',
      },
      fontFamily: {
        display: ['var(--font-display)', 'Fraunces', 'serif'],
        body: ['var(--font-body)', 'Inter', 'sans-serif'],
        fraunces: ['var(--font-display)', 'Fraunces', 'serif'],
        hanken: ['var(--font-body)', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        hero: ['4rem', { lineHeight: '1.05', letterSpacing: '-0.02em', fontWeight: '600' }],
        'hero-mobile': ['2.5rem', { lineHeight: '1.05', letterSpacing: '-0.02em', fontWeight: '600' }],
        'section-head': ['2.5rem', { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '600' }],
        'metric-numeral': ['3.5rem', { lineHeight: '1', fontWeight: '700' }],
        'report-stat': ['2.5rem', { lineHeight: '1', fontWeight: '700' }],
        'card-title': ['1rem', { lineHeight: '1.5', fontWeight: '600' }],
        'card-summary': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'card-meta': ['0.8125rem', { lineHeight: '1.4', fontWeight: '400' }],
        badge: ['0.75rem', { lineHeight: '1', fontWeight: '600' }],
        confidence: ['1.75rem', { lineHeight: '1', fontWeight: '600' }],
        'section-label': ['0.9375rem', { lineHeight: '1.5', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
