apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rise-api-canary-ingress
  namespace: rise-prod
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx
  rules:
    - host: api.rise.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rise-api-canary
                port:
                  number: 8000
